# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WscliATV204 < Formula
  desc "A command-line WebSocket client"
  homepage "https://github.com/akshaykhairmode/wscli"
  version "2.0.4"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.4/wscli_Darwin_x86_64.tar.gz"
      sha256 "f439e421684ad1a57c020b63d8fa40ddd931474ab3c0268ef262921cfdd324c7"

      def install
        bin.install "wscli"
      end
    end
    on_arm do
      url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.4/wscli_Darwin_arm64.tar.gz"
      sha256 "a6101aef33d7a367dede72a97a4114f54cdd2b431a2d937af123eb237f314696"

      def install
        bin.install "wscli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.4/wscli_Linux_x86_64.tar.gz"
        sha256 "abe4f9785277a852ea77141e8df883489d9c718ea4bb4edccca8c43a28737c61"

        def install
          bin.install "wscli"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.4/wscli_Linux_armv6.tar.gz"
        sha256 "5b92ac546648b7e396f5d46ac869464afec7ecfb5503ac1f8b87338104296f4a"

        def install
          bin.install "wscli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.4/wscli_Linux_arm64.tar.gz"
        sha256 "6a67d3330391bf2f2140015faa1d48c804806561632ac87535bfff901877390a"

        def install
          bin.install "wscli"
        end
      end
    end
  end
end
