# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wscli@v2011 < Formula
  desc "A command-line WebSocket client"
  homepage "https://github.com/akshaykhairmode/wscli"
  version "2.0.11"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.11/wscli_Darwin_x86_64.tar.gz"
      sha256 "c04fd658e2646e33a4555edc896387fe34d0c21ae459471493d852bf708a653e"

      define_method(:install) do
        bin.install "wscli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.11/wscli_Darwin_arm64.tar.gz"
      sha256 "de00e7955028859d2526068b491fd6298366afed8443f9ed8fb7e13d8958a6a5"

      define_method(:install) do
        bin.install "wscli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.11/wscli_Linux_x86_64.tar.gz"
      sha256 "5dbb3f7aa256678fe8072911347df5e0fdbbd02c3af7ba25bd5386b6ecaac130"
      define_method(:install) do
        bin.install "wscli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.11/wscli_Linux_armv6.tar.gz"
      sha256 "f6d1217d07c0a36abbab7a170e01b84b249e478d83b2256b002c6678b5d4bcad"
      define_method(:install) do
        bin.install "wscli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.11/wscli_Linux_arm64.tar.gz"
      sha256 "ecd4f9f86e80f6d89c6566a924455241633d5a8a6fb9f0b3f66051f0131abfe0"
      define_method(:install) do
        bin.install "wscli"
      end
    end
  end
end
