# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wscli@v2014 < Formula
  desc "A command-line WebSocket client"
  homepage "https://github.com/akshaykhairmode/wscli"
  version "2.0.14"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.14/wscli_Darwin_x86_64.tar.gz"
      sha256 "b318be1c8944086149e742f261db612091ecad5c91b4c77076a7b8106cdbfcd5"

      define_method(:install) do
        bin.install "wscli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.14/wscli_Darwin_arm64.tar.gz"
      sha256 "1c2919f60b3948697ef65c5ddabf9eb45129c6f6588dcbad0130d95136ab5226"

      define_method(:install) do
        bin.install "wscli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.14/wscli_Linux_x86_64.tar.gz"
      sha256 "4b8e7f3fc9e6a58f0bcbadccf93c1ad4e62543b6db648cc437870a47a345692f"
      define_method(:install) do
        bin.install "wscli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.14/wscli_Linux_armv6.tar.gz"
      sha256 "e4764a7d306c51161d2c26fc7505158d9054b41dc5fe4abd434441443c868817"
      define_method(:install) do
        bin.install "wscli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.14/wscli_Linux_arm64.tar.gz"
      sha256 "894ec8387736e189d42fab87eb3945603ba0fcdde9e11faf4d899893386263af"
      define_method(:install) do
        bin.install "wscli"
      end
    end
  end
end
