# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wscli@v2013 < Formula
  desc "A command-line WebSocket client"
  homepage "https://github.com/akshaykhairmode/wscli"
  version "2.0.13"
  license "GPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.13/wscli_Darwin_x86_64.tar.gz"
      sha256 "9eb9123708aa245c3c3d11d56f3d19369e61c9057208c81b30318093020f791b"

      define_method(:install) do
        bin.install "wscli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.13/wscli_Darwin_arm64.tar.gz"
      sha256 "99d99383d69c5caa785bd1df8cc7ea8bc098d65d27e87ae3dc953adc752ca139"

      define_method(:install) do
        bin.install "wscli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.13/wscli_Linux_x86_64.tar.gz"
      sha256 "56c0f453a85a9392ea3681c2b04b0b12254a6e18348efeaf06288251f5a2b20b"
      define_method(:install) do
        bin.install "wscli"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.13/wscli_Linux_armv6.tar.gz"
      sha256 "09112ea4fca7c5a48f21657e91ffdb0a9c0455cc0a9ef50c92f6f38c7a1e7781"
      define_method(:install) do
        bin.install "wscli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.13/wscli_Linux_arm64.tar.gz"
      sha256 "46cd3242febabc20eaf00eb59d9a0584e23069ac8e1937efbd28ca472c6edd41"
      define_method(:install) do
        bin.install "wscli"
      end
    end
  end
end
