# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WscliAT2 < Formula
  desc "A command-line WebSocket client"
  homepage "https://github.com/akshaykhairmode/wscli"
  version "2.0.1"
  license "GPL-3.0"

  on_macos do
    on_intel do
      url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.1/wscli_Darwin_x86_64.tar.gz"
      sha256 "23fbaaccfdb18097806171979eab88c8f022103b0b21c4b953c33cc5695f4f41"

      def install
        bin.install "wscli"
      end
    end
    on_arm do
      url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.1/wscli_Darwin_arm64.tar.gz"
      sha256 "9f3e8e8348abd47936e7281a3f1b8a9ba72126aa5d4666fee9c6028a7062040d"

      def install
        bin.install "wscli"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.1/wscli_Linux_x86_64.tar.gz"
        sha256 "301c2099ee7742af73010b7b9b05f1a609d4ff363406667f2cc15d53440553fe"

        def install
          bin.install "wscli"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.1/wscli_Linux_armv6.tar.gz"
        sha256 "f07cc2e02a2a8678a40511c316ac41975bc4d95652463ddfd54b0a13d1ca7d86"

        def install
          bin.install "wscli"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/akshaykhairmode/wscli/releases/download/v2.0.1/wscli_Linux_arm64.tar.gz"
        sha256 "ed626a9e55fef72467c597e396e724032a629bc7d2c8fe1fa6cc60dd453d7dc2"

        def install
          bin.install "wscli"
        end
      end
    end
  end
end
